add cl include dir

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -34,6 +34,12 @@ cd ${0%/*} || exit 1    # Run from this directory
     exit 1
 }
 
+[ -n "$CL_INC_DIR" ] || {
+    echo "Allwmake error: CL_INC_DIR not set"
+    echo "    Set this environment variable to enable proper compilation"
+    exit 1
+}
+
 [ -n "$FOAM_EXT_LIBBIN" ] || {
     echo "Allwmake error: FOAM_EXT_LIBBIN not set"
     echo "    Check the OpenFOAM entries in your dot-files and source them."
